#!/bin/bash
alias ls=rm 0-alias 100-decimal_to_hexadecimal 12-combinations 13-print_float 1-hello_you 2-path 3-paths 4-global_variables 5-local_variables 6-create_local_variable 7-create_global_variable 8-true_knowledge README.md
